name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["main"]
    types: ["completed"]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - uses: ko-build/setup-ko@v0.8
      - run: ko build